INCLUDE_PATH    := ./ ../common/ ../external/include/ 
SOURCE_PATH     := ./ ../common/
DEPENDENCY_PATH := dep
OBJECT_PATH     := obj

# EXTERNAL_LIBS := $(wildcard ../external/lib/*.a)
LDLIBS := -lm -lpthread -lcholmod -lumfpack

CFLAGS += -O3

include ../makefile.mk
